/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'santosh' at '12/8/16 2:47 PM' with Gradle 3.0
 *
 * @author santosh, @date 12/8/16 2:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
